Hw04 express
17eugene/nodejs-homework-template pull request #3
Opened 2021-11-23 00:35 UTC by 17eugene

2021-11-23 19:16 UTC, KirillKulakow commented on controllers/auth-controllers/getCurrentCtrl.js
> +    await usersModel.findById(_id);
зачем этот запрос в БД?

2021-11-23 19:22 UTC, KirillKulakow requested changes
need fix

2021-11-23 19:22 UTC, KirillKulakow commented on controllers/contacts-controllers/getAll-ctrl.js
> +    if (favorite === "true") {
много лишнего кода
```
const favoriteContacts = await contactsModel
         .find({ owner: _id, favorite }, "_id name email phone owner", {
           skip,
           limit: Number(limit),
         })
         .populate("owner", "_id email");
```

2021-11-23 19:22 UTC, KirillKulakow commented on controllers/contacts-controllers/getAll-ctrl.js
> +    if (favorite === "true") {
можно только один запрос делать

2021-11-23 19:22 UTC, KirillKulakow commented on controllers/contacts-controllers/getAll-ctrl.js
> +    if (favorite === "true") {
и сделай проверку page и limit на число - если не число вернуть ошибку bad Request

2021-11-23 19:22 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(" ");
если сделать запрос на список контактов без авторизации - приложение сломается

2021-11-23 19:23 UTC, KirillKulakow commented
И исправь методы удалить/изменить/просмотреть по ид - чтобы их нельзя было удалить юзеру который не является собственником контакта

2021-11-24 15:08 UTC, 17eugene commented on controllers/auth-controllers/getCurrentCtrl.js
> +    await usersModel.findById(_id);
Правильно я понимаю что этот запрос не нужен, потому что поиск по id происходит в мидлваре authenticate?

2021-11-25 20:43 UTC, KirillKulakow commented on controllers/auth-controllers/getCurrentCtrl.js
> +    await usersModel.findById(_id);
я просто не понимаю зачем - ты просто делаешь запрос данных в базе и при этом ответ нигде не используешь

2021-11-25 20:45 UTC, KirillKulakow commented on controllers/auth-controllers/getCurrentCtrl.js
> +const getCurrentCtrl = async (req, res, next) => {
async здесь не нужен, так же как и try catch
так как внутри у тебя нет никаких асинхронных операций

2021-11-25 20:50 UTC, KirillKulakow commented on controllers/contacts-controllers/getAll-ctrl.js
> +    if (Number.isNaN(page) || Number.isNaN(limit)) {
лучше использовать просто isNaN
если использовать Number.isNaN - true будет только если внутри будет именно NaN
чтобы корректно работал нужно написать Number.isNaN (+`${page}`) тогда корректно будет работать

2021-11-25 20:52 UTC, KirillKulakow requested changes
Need fix

2021-11-26 20:02 UTC, KirillKulakow approved these changes

2021-11-28 12:02 UTC, merged